{% set versions = {
    "1.104": "c4b1f675f02787003c42c600051c0e23f23680ee454f9f8e34875755563dbb77"
} %}


{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

{% set name = environ.get('ANACONDA_PACKAGE', "fastjet-contrib")|string|lower %}

package:
  name: {{ name }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace("-", ".") }}

source:
  url: "http://fastjet.hepforge.org/contrib/downloads/fjcontrib-{{ version }}.tar.gz"
  {% if versions.get(version, None) %}
  sha256: {{ versions.get(version) }}
  {% endif %}

build:
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x.x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}

    - make
    - gnuconfig

  host:
    - fastjet

  run:
    - fastjet

about:
  home: "https://fastjet.hepforge.org/contrib/"
  license: "GPL-2.0"
  summary: "The fastjet-contrib space is intended to provide a common location for access to 3rd party extensions of FastJet."

extra:
  recipe-maintainers:
    - meiyasan
